import { MetadataRoute } from "next";
import { sportsPages } from "@/lib/sports-pages";
import { caseStudies } from "@/lib/case-studies";
import { pseoPages } from "@/lib/pseo";
import { getArticles } from "@/lib/sanity/content";

function uniqueByUrl(routes: MetadataRoute.Sitemap): MetadataRoute.Sitemap {
  const seen = new Set<string>();
  return routes.filter((route) => {
    if (seen.has(route.url)) return false;
    seen.add(route.url);
    return true;
  });
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = "https://www.poxiol.com";
  const articles = await getArticles();

  // 1. Static Core Pages
  const staticPages = [
    "",
    "/solutions/",
    "/products/",
    "/design-gallery/",
    "/factory/",
    "/customization/",
    "/about/",
    "/contact/",
    "/free-mockup/",
    "/get-quote/",
    "/sample-order/",
    "/oem-odm/",
    "/resources/",
    "/blog/",
    "/faq/",
    "/fabric-guide/",
    "/printing-guide/",
    "/certificates-testing/",
    "/quality-control-process/",
    "/manufacturing/",
    "/guides/b2b-sourcing-faq/",
    "/privacy-policy/",
    "/terms/",
    "/intellectual-property-policy/",
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: route === "" ? 1.0 : 0.8,
  }));

  // 2. Product Category Pages
  const productRoutes = sportsPages.map((sport) => ({
    url: `${baseUrl}/${sport.slug}/`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }));

  // 3. Project Detail Pages
  const projectRoutes = caseStudies.map((project) => ({
    url: `${baseUrl}/projects/${project.slug}/`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  // 4. PSEO landing pages are generated by app/[slug], not the resource route.
  const pseoRoutes = pseoPages.map((page) => ({
    url: `${baseUrl}/${page.slug}/`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.6,
  }));

  // 5. Article URLs use the same CMS resolver as each route's generateStaticParams.
  const cmsArticleRoutes = articles.map((article) => {
    const section = article.articleType === "blog" ? "blog" : article.articleType === "resource" ? "resources" : "guides";
    return {
      url: `${baseUrl}/${section}/${article.slug}/`,
      lastModified: article.updatedAt ? new Date(article.updatedAt) : new Date(),
      changeFrequency: "weekly" as const,
      priority: article.articleType === "guide" ? 0.8 : 0.7,
    };
  });
  return uniqueByUrl([...staticPages, ...productRoutes, ...projectRoutes, ...pseoRoutes, ...cmsArticleRoutes]);
}
