import { MetadataRoute } from "next";
import { caseStudies } from "@/lib/case-studies";
import { sportsPages } from "@/lib/sports-pages";
import { pseoPages } from "@/lib/pseo";
import { getArticles, getProductCategories } from "@/lib/sanity/content";
import { publicLegalPolicyRoutes } from "@/lib/legal-release";
import { DEDICATED_GUIDE_SLUGS } from "@/lib/guides/routes";
import { publicSectionDecision, type PublicSectionId } from "@/lib/release/publication-policy";

export const dynamic = "force-static";

const releaseLastModified = new Date("2026-08-29T00:00:00.000Z");

const governedStaticPages: Array<{route: string; policy: PublicSectionId}> = [
  {route: "/design-gallery/", policy: "design-planning"},
  {route: "/factory/", policy: "manufacturing-planning"},
  {route: "/manufacturing/", policy: "manufacturing-planning"},
  {route: "/quality-control-process/", policy: "quality-control-planning"},
];

function uniqueByUrl(routes: MetadataRoute.Sitemap): MetadataRoute.Sitemap {
  const seen = new Set<string>();
  return routes.filter((route) => {
    if (seen.has(route.url)) return false;
    seen.add(route.url);
    return true;
  });
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = "https://www.poxiol.com";
  const [articles, categories] = await Promise.all([getArticles(), getProductCategories()]);

  // 1. Static Core Pages
  const staticPages = [
    "",
    "/solutions/",
    "/products/",
    "/custom-baseball-softball-uniforms/",
    "/customization/",
    "/about/",
    "/contact/",
    "/free-mockup/",
    "/get-quote/",
    "/sample-order/",
    "/oem-odm/",
    "/resources/",
    "/blog/",
    "/faq/",
    "/fabric-guide/",
    "/printing-guide/",
    "/certificates-testing/",
    "/youth-team-uniforms/",
    "/school-teamwear/",
    "/club-teamwear-program/",
    "/private-label-teamwear/",
    "/shipping-after-sales/",
    ...governedStaticPages
      .filter(({policy}) => publicSectionDecision(policy) !== "WITHHELD")
      .map(({route}) => route),
    ...DEDICATED_GUIDE_SLUGS.map((slug) => `/guides/${slug}/`),
    ...publicLegalPolicyRoutes(),
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: releaseLastModified,
    changeFrequency: "weekly" as const,
    priority: route === "" ? 1.0 : 0.8,
  }));

  // 2. Product Category Pages
  const exportedCategorySlugs = new Set(sportsPages.map((page) => page.slug.replace(/^products\//, "")));
  const productRoutes = categories.filter((category) => exportedCategorySlugs.has(category.slug) && !category.seo.noIndex).map((category) => ({
    url: `${baseUrl}/products/${category.slug}/`,
    lastModified: releaseLastModified,
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }));

  // 3. Project Detail Pages
  const projectRoutes = caseStudies.map((project) => ({
    url: `${baseUrl}/projects/${project.slug}/`,
    lastModified: releaseLastModified,
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  // 4. PSEO landing pages are generated by app/[slug], not the resource route.
  const pseoRoutes = pseoPages.map((page) => ({
    url: `${baseUrl}/${page.slug}/`,
    lastModified: releaseLastModified,
    changeFrequency: "weekly" as const,
    priority: 0.6,
  }));

  // 5. Article URLs use the same CMS resolver as each route's generateStaticParams.
  const cmsArticleRoutes = articles.map((article) => {
    const section = article.articleType === "blog" ? "blog" : article.articleType === "resource" ? "resources" : "guides";
    return {
      url: `${baseUrl}/${section}/${article.slug}/`,
      lastModified: article.updatedAt ? new Date(article.updatedAt) : releaseLastModified,
      changeFrequency: "weekly" as const,
      priority: article.articleType === "guide" ? 0.8 : 0.7,
    };
  });
  return uniqueByUrl([...staticPages, ...productRoutes, ...projectRoutes, ...pseoRoutes, ...cmsArticleRoutes]);
}
