export type FAQCategory = {
  category: string;
  items: { question: string; answer: string }[];
};

export const faqData: FAQCategory[] = [
  {
    category: "General Teamwear",
    items: [
      { question: "What is custom teamwear?", answer: "Custom teamwear refers to sports uniforms and apparel designed specifically for a team, club, school, academy, distributor or sportswear brand, including logos, colors, player names, numbers and sponsor graphics." },
      { question: "Who can order custom teamwear from POXIOL?", answer: "POXIOL works with sports clubs, schools, academies, universities, distributors, sportswear brands and event organizers worldwide." },
      { question: "What sports uniforms do you manufacture?", answer: "POXIOL manufactures basketball uniforms, soccer kits, baseball jerseys, volleyball uniforms, rugby apparel, running wear, esports jerseys and other team sports apparel." },
      { question: "Do you offer OEM manufacturing?", answer: "Yes. POXIOL supports OEM sportswear manufacturing with custom branding, private labels, packaging and product specifications." },
      { question: "Do you offer ODM manufacturing?", answer: "Yes. ODM services allow buyers to customize proven product structures while reducing development time." },
      { question: "Can I order samples before bulk production?", answer: "Yes. Sample production is available to verify fabric, sizing, printing and construction quality before bulk production." },
      { question: "Do you support private label sportswear?", answer: "Yes. POXIOL provides custom neck labels, woven labels, hang tags, brand stickers and branded packaging." },
      { question: "What is your minimum order quantity?", answer: "MOQ varies depending on product type and customization requirements. Flexible MOQ options are available for many projects." },
      { question: "Do you ship worldwide?", answer: "Yes. POXIOL ships globally through express, air freight and sea freight options." },
      { question: "Can I reorder the same design later?", answer: "Yes. Design files can be retained for repeat production and future teamwear programs." },
      { question: "Can POXIOL help with design mockups?", answer: "Yes. POXIOL provides mockup support to help buyers preview custom teamwear before production." },
      { question: "What information should I provide for a quote?", answer: "Please provide sport type, product type, quantity, sizes, design requirements, logo files, delivery country and timeline." },
      { question: "Can I use my own team logo?", answer: "Yes. Customer-provided team logos and brand assets can be used when the buyer has permission to use them." },
      { question: "Can sponsor logos be added?", answer: "Yes. Sponsor logos can be included in jersey designs, subject to buyer permission and design requirements." },
      { question: "Can I customize colors?", answer: "Yes. Team colors and brand color references can be customized before production." },
    ],
  },
  {
    category: "Basketball",
    items: [
      { question: "What basketball uniforms do you make?", answer: "POXIOL manufactures basketball jerseys, basketball shorts, reversible basketball uniforms and warm-up apparel." },
      { question: "What is the best fabric for basketball jerseys?", answer: "We recommend Mesh, Interlock, or Quick-Dry polyester for breathable, high-performance basketball uniforms." },
      { question: "Do you offer reversible basketball uniforms?", answer: "Yes. Custom reversible basketball uniforms are available for training and competition." },
      { question: "Can I add player names and numbers?", answer: "Yes. Player names and numbers can be customized on basketball jerseys." },
      { question: "Do you support youth basketball programs?", answer: "Yes. POXIOL provides youth sizes for schools and basketball academies." },
      { question: "Can I order basketball shorts separately?", answer: "Yes. Basketball jerseys and shorts can be ordered as sets or individual items." },
      { question: "What printing is best for basketball uniforms?", answer: "Sublimation printing is recommended for durable, full-color basketball designs." },
      { question: "Do you make custom basketball warm-up suits?", answer: "Yes. Custom tracksuits and warm-up apparel are available for basketball teams." },
      { question: "Can I customize collar styles?", answer: "Yes. V-neck, round neck and other collar options are available for basketball jerseys." },
      { question: "What is the production time for basketball uniforms?", answer: "Standard production time is typically 10-14 days after design approval." },
    ],
  },
  {
    category: "Soccer",
    items: [
      { question: "Do you manufacture soccer kits?", answer: "Yes. POXIOL makes soccer jerseys, soccer shorts, socks and training apparel." },
      { question: "What fabric is best for soccer jerseys?", answer: "Interlock, Bird Eye, and lightweight Mesh polyesters are commonly used for soccer kits." },
      { question: "Can I add sponsor logos to soccer jerseys?", answer: "Yes. Sponsor logos, club crests, names and numbers can be fully customized." },
      { question: "Do you make goalkeeper uniforms?", answer: "Yes. Custom goalkeeper jerseys and padded shorts/pants are available." },
      { question: "Do you support youth soccer academies?", answer: "Yes. We provide youth and adult sizes for soccer organizations." },
      { question: "Can I order full soccer team kits?", answer: "Yes. Complete kits including jerseys, shorts and socks can be manufactured." },
      { question: "What printing method is used for soccer?", answer: "Sublimation is the primary method for soccer jerseys due to durability and vibrant colors." },
      { question: "Can I customize soccer shorts?", answer: "Yes. Soccer shorts can be customized with logos, numbers and club colors." },
      { question: "Do you make custom soccer training bibs?", answer: "Yes. Branded training bibs and pinnies are available." },
      { question: "How long does soccer kit production take?", answer: "Bulk soccer orders typically take 10-20 days depending on volume." },
    ],
  },
  {
    category: "Baseball & Softball",
    items: [
      { question: "What baseball jerseys do you offer?", answer: "POXIOL offers full-button, two-button, and v-neck baseball jerseys." },
      { question: "What fabric is used for baseball uniforms?", answer: "Durable, high-density polyesters like 220gsm Interlock are common for baseball." },
      { question: "Do you make custom baseball pants?", answer: "Yes. Custom baseball pants with reinforced knees and piping are available." },
      { question: "Are softball jerseys available?", answer: "Yes. We offer specialized cuts for women's and girls' softball teams." },
      { question: "Can I add player names to baseball jerseys?", answer: "Yes. Names and numbers can be added via sublimation or heat transfer." },
      { question: "Do you make custom baseball caps?", answer: "Yes. Branded baseball caps can be included in team packages." },
      { question: "What is the MOQ for baseball uniforms?", answer: "Flexible MOQ options are available for baseball club programs." },
      { question: "Can I customize sleeve lengths?", answer: "Yes. Standard and custom sleeve options are available." },
      { question: "Do you provide baseball mockups?", answer: "Yes. Custom 3D mockups are provided for design verification." },
      { question: "How long is baseball uniform shipping?", answer: "Express shipping typically takes 3-7 business days." },
    ],
  },
  {
    category: "Volleyball",
    items: [
      { question: "Do you manufacture volleyball uniforms?", answer: "Yes. POXIOL makes volleyball jerseys, shorts and spandex apparel." },
      { question: "What fabric is best for volleyball?", answer: "Stretch-performance polyesters and spandex blends are ideal for volleyball mobility." },
      { question: "Are sleeveless volleyball jerseys available?", answer: "Yes. Sleeveless, cap-sleeve and long-sleeve options are available." },
      { question: "Can I customize libero jerseys?", answer: "Yes. Libero jerseys can be customized with contrasting colors and designs." },
      { question: "Do you offer youth volleyball sizes?", answer: "Yes. Youth and adult sizes are available for volleyball teams." },
      { question: "What is the MOQ for volleyball uniforms?", answer: "Flexible ordering options are supported for volleyball clubs." },
      { question: "Can I add player numbers to the front and back?", answer: "Yes. Numbering standards for volleyball are fully supported." },
      { question: "Do you make custom volleyball shorts?", answer: "Yes. Both loose-fit and tight-fit (spandex) volleyball shorts are available." },
      { question: "Is sublimation used for volleyball apparel?", answer: "Yes. Sublimation ensures vibrant, durable designs for volleyball gear." },
      { question: "What is the volleyball uniform turnaround time?", answer: "Typically 10-14 days after design finalization." },
    ],
  },
  {
    category: "Manufacturing",
    items: [
      { question: "Where are your products manufactured?", answer: "POXIOL operates professional manufacturing facilities specializing in sportswear." },
      { question: "Do you handle the entire production process?", answer: "Yes. We manage fabric sourcing, printing, cutting, sewing, QC and logistics." },
      { question: "What is your quality control process?", answer: "We perform multi-stage inspections on fabric, printing, assembly and final packing." },
      { question: "Can you produce custom patterns?", answer: "Yes. Our pattern makers can develop custom fits based on brand requirements." },
      { question: "Do you support sustainable manufacturing?", answer: "We continuously look for ways to improve efficiency and reduce waste in our factory." },
      { question: "Can I visit your factory?", answer: "Factory visits can be arranged for bulk buyers and strategic partners." },
      { question: "What machines do you use?", answer: "We use high-precision sublimation printers, heat presses and professional sewing equipment." },
      { question: "Do you provide production updates?", answer: "Yes. Progress updates can be shared during the manufacturing cycle." },
      { question: "Can you handle peak season demand?", answer: "We plan capacity carefully to maintain reliable delivery during high-demand periods." },
      { question: "Do you offer design consulting?", answer: "Yes. Our technical team can advise on construction and printing feasibility." },
    ],
  },
  {
    category: "Fabric",
    items: [
      { question: "What is moisture-wicking technology?", answer: "It is a fabric treatment or construction that moves sweat away from the body." },
      { question: "Is your fabric breathable?", answer: "Yes. We use performance polyesters engineered for optimal airflow." },
      { question: "Does the fabric shrink?", answer: "Our high-grade polyesters are pre-shrunk and maintain their shape after washing." },
      { question: "Can I choose fabric weight?", answer: "Yes. Different weights (gsm) are available based on sport and preference." },
      { question: "Do you offer eco-friendly fabrics?", answer: "Recycled polyester options are available for specific projects." },
      { question: "How should I care for the uniforms?", answer: "Machine wash cold and air dry to maintain print and fabric integrity." },
      { question: "Is the fabric suitable for sensitive skin?", answer: "Our fabrics are soft-touch and designed for athletic comfort." },
      { question: "Do you offer anti-bacterial treatments?", answer: "Anti-microbial and anti-odor treatments can be added to many fabrics." },
      { question: "What is the difference between Mesh and Interlock?", answer: "Mesh has visible holes for maximum airflow; Interlock is smooth and solid." },
      { question: "Can I request fabric swatches?", answer: "Fabric swatches can be provided to bulk buyers for quality verification." },
    ],
  },
  {
    category: "Printing",
    items: [
      { question: "What is sublimation printing?", answer: "A process where dye is heat-transferred into the fabric fibers for permanent color." },
      { question: "Will the design fade over time?", answer: "No. Sublimated designs do not fade, crack or peel." },
      { question: "Can I print gradients and fine details?", answer: "Yes. Sublimation supports high-resolution graphics and complex colors." },
      { question: "Do you offer screen printing?", answer: "Yes. Screen printing is available for specific merchandise and simple designs." },
      { question: "Is embroidery available?", answer: "Yes. Embroidery is often used for club polos, jackets and premium branding." },
      { question: "Can you match my brand colors?", answer: "Yes. We use color matching standards to ensure brand consistency." },
      { question: "What logo formats do you accept?", answer: "Vector files (AI, EPS, SVG, PDF) are preferred for best results." },
      { question: "Can I combine printing methods?", answer: "Yes. For example, a sublimated jersey can have an embroidered club crest." },
      { question: "Is the ink safe?", answer: "We use high-quality, eco-friendly inks that are safe for skin contact." },
      { question: "Does printing affect breathability?", answer: "Sublimation does not clog pores, maintaining full fabric breathability." },
    ],
  },
  {
    category: "Shipping",
    items: [
      { question: "Which couriers do you use?", answer: "We primarily use DHL, FedEx, UPS and TNT for express international shipping." },
      { question: "How long is express shipping?", answer: "Typically 3-7 business days depending on the destination country." },
      { question: "Do you provide tracking numbers?", answer: "Yes. Tracking details are provided as soon as the order is dispatched." },
      { question: "Can I use my own shipping agent?", answer: "Yes. We can coordinate with your nominated freight forwarder." },
      { question: "Do you handle customs clearance?", answer: "We provide all necessary documents; the buyer is responsible for local import duties." },
      { question: "Is the shipping insured?", answer: "Insurance options can be discussed for high-value bulk shipments." },
      { question: "Can you drop-ship to my clients?", answer: "We primarily focus on bulk B2B shipping but can discuss specific logistics needs." },
      { question: "Do you ship to remote locations?", answer: "We can ship anywhere covered by major international couriers." },
      { question: "How are products packed?", answer: "Items are individually polybagged and securely boxed for transit." },
      { question: "Can I change my shipping address?", answer: "Address changes must be confirmed before the order is dispatched." },
    ],
  },
  {
    category: "Pricing & Payments",
    items: [
      { question: "How do I get a price list?", answer: "Pricing is project-based; please contact us for a customized quote." },
      { question: "Do you offer volume discounts?", answer: "Yes. Larger quantities for leagues and distributors receive better pricing." },
      { question: "What payment methods do you accept?", answer: "We accept Bank Transfers (T/T), Western Union and other secure options." },
      { question: "What are your payment terms?", answer: "Standard terms are a 50% deposit to start and 50% balance before shipping." },
      { question: "Are there any hidden costs?", answer: "We provide transparent quotes including production and estimated shipping." },
      { question: "Is design work included in the price?", answer: "Basic design and mockup support are included in most teamwear quotes." },
      { question: "Can I get a pro-forma invoice?", answer: "Yes. PIs are issued for all confirmed orders." },
      { question: "Do you offer sponsorship pricing?", answer: "We focus on fair factory pricing but can discuss partnerships for large academies." },
      { question: "Is pricing stable for reorders?", answer: "We aim for price stability but adjustments may occur based on raw material costs." },
      { question: "How do I confirm my order?", answer: "Orders are confirmed upon receipt of deposit and final artwork approval." },
    ],
  },
];
