import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'

const hero = readFileSync('components/v8/V8Hero.tsx', 'utf8')
const homepage = readFileSync('components/v8/HomepageV8.tsx', 'utf8')
const customerSegmentation = readFileSync('components/v8/CustomerSegmentation.tsx', 'utf8')
const buyerPage = readFileSync('components/v8/V8BuyerLandingPage.tsx', 'utf8')
const processTimeline = readFileSync('components/v8/ProcessTimeline.tsx', 'utf8')
const cardGrid = readFileSync('components/v8/CardGrid.tsx', 'utf8')
const ui = readFileSync('components/ui.tsx', 'utf8')

assert.match(hero, /overflow-x-hidden/, 'V8 Hero must guard against horizontal overflow.')
assert.match(hero, /min-w-0/, 'Hero columns must be allowed to shrink on mobile.')
assert.match(hero, /break-words/, 'Long B2B headings must wrap safely.')
assert.match(hero, /text-\[2rem\][^"']*min-\[390px\]:text-4xl/, 'Hero headings must remain word-readable below 390px.')
assert.match(hero, /min-h-14/, 'Hero CTA touch targets must be at least 56px high.')
assert.match(hero, /min-\[360px\]:flex-row/, 'Hero CTAs must share one row from 360px so the fixed mobile bar does not cover the secondary action.')
assert.match(hero, /min-\[360px\]:px-4/, 'Hero CTAs need compact horizontal padding on narrow mobile screens.')
assert.match(hero, /min-\[360px\]:py-2/, 'Wrapped narrow-screen CTA labels must stay inside the 56px touch target.')
assert.match(hero, /pb-28[^"']*md:pb-16/, 'Mobile Hero must reserve space above the fixed CTA bar.')
assert.match(hero, /lg:grid-cols-\[1\.2fr_0\.8fr\]/, 'Desktop Hero copy needs enough width to keep CTA above the fold.')
assert.match(hero, /md:pt-10/, 'Desktop Hero must keep the primary CTA inside a 720px first screen.')
assert.match(hero, /xl:text-5xl/, 'Desktop Hero heading must not grow beyond the conversion-safe first screen.')
assert.doesNotMatch(hero, /min-h-screen|h-screen/, 'Hero height must follow content rather than force a viewport height.')
assert.doesNotMatch(homepage, /overflow-x-auto/, 'Homepage V8 sections must not introduce horizontal scrolling.')
assert.match(customerSegmentation, /bg-white/, 'Customer segmentation needs an explicit light background for readable dark headings.')
assert.match(customerSegmentation, /text-neutral-950/, 'Customer segmentation must preserve readable contrast on its light background.')
assert.doesNotMatch(buyerPage, /overflow-x-auto/, 'Buyer pages must not introduce horizontal scrolling sections.')
assert.match(processTimeline, /grid gap-5 md:grid-cols-2 lg:grid-cols-4/, 'Process cards must remain single-column on mobile.')
assert.match(cardGrid, /grid gap-5 md:grid-cols-2 lg:grid-cols-3/, 'Buyer problem cards must remain single-column on mobile.')
assert.match(ui, /break-words/, 'Shared section headings must wrap long authority-page words safely on narrow mobile screens.')
assert.match(ui, /text-3xl[^"']*min-\[390px\]:text-4xl/, 'Shared section headings must remain word-readable below 390px.')

console.log('POXIOL V8 mobile layout checks passed.')
