import {defineField, defineType} from 'sanity'
import {DocumentIcon} from '@sanity/icons'
import {createRiskValidation} from '../validation'

export const article = defineType({
  name: 'article',
  title: 'Articles and Guides',
  type: 'document',
  icon: DocumentIcon,
  groups: [
    {name: 'basic', title: 'Basic'},
    {name: 'content', title: 'Content'},
    {name: 'authoring', title: 'Authoring and review'},
    {name: 'relations', title: 'Relations'},
    {name: 'display', title: 'Display'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', group: 'basic', validation: (Rule) => Rule.required()}),
    defineField({name: 'slug', title: 'URL slug', type: 'slug', group: 'basic', options: {source: 'title', maxLength: 80}, validation: (Rule) => Rule.required()}),
    defineField({name: 'articleType', title: 'Article type', type: 'string', group: 'basic', options: {list: [
      {title: 'Blog', value: 'blog'},
      {title: 'Buying Guide', value: 'guide'},
      {title: 'Technical Guide', value: 'guide'},
      {title: 'Checklist', value: 'guide'},
      {title: 'Comparison', value: 'guide'},
      {title: 'Resource', value: 'resource'},
      {title: 'SEO Article', value: 'blog'},
      {title: 'FAQ Hub', value: 'resource'},
    ]}, validation: (Rule) => Rule.required()}),
    defineField({name: 'excerpt', title: 'Excerpt', type: 'text', rows: 2, group: 'basic'}),
    defineField({name: 'featuredImage', title: 'Featured image', type: 'imageWithAlt', group: 'basic'}),
    defineField({name: 'body', title: 'Body', type: 'portableText', group: 'content'}),
    defineField({name: 'keyTakeaways', title: 'Key takeaways', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'author', title: 'Author', type: 'reference', to: [{type: 'author'}], group: 'authoring'}),
    defineField({name: 'reviewedBy', title: 'Reviewed by', type: 'reference', to: [{type: 'author'}], group: 'authoring'}),
    defineField({name: 'publishedAt', title: 'Published at', type: 'datetime', group: 'authoring'}),
    defineField({name: 'updatedAt', title: 'Updated at', type: 'datetime', group: 'authoring'}),
    defineField({name: 'methodology', title: 'Methodology / data sources', type: 'text', rows: 3, group: 'authoring'}),
    defineField({name: 'references', title: 'References', type: 'array', of: [{type: 'url'}], group: 'authoring'}),
    defineField({name: 'relatedProducts', title: 'Related products', type: 'array', of: [{type: 'reference', to: [{type: 'product'}]}], group: 'relations'}),
    defineField({name: 'relatedCategories', title: 'Related categories', type: 'array', of: [{type: 'reference', to: [{type: 'productCategory'}]}], group: 'relations'}),
    defineField({name: 'relatedCaseStudies', title: 'Related case studies', type: 'array', of: [{type: 'reference', to: [{type: 'caseStudy'}]}], group: 'relations'}),
    defineField({name: 'relatedArticles', title: 'Related articles', type: 'array', of: [{type: 'reference', to: [{type: 'article'}]}], group: 'relations'}),
    defineField({name: 'faqReferences', title: 'Related FAQ', type: 'array', of: [{type: 'faqReference'}], group: 'relations'}),
    defineField({name: 'cta', title: 'CTA', type: 'callToAction', group: 'display'}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', initialValue: false, group: 'display'}),
    defineField({name: 'displayOrder', title: 'Display order', type: 'number', initialValue: 0, group: 'display'}),
    defineField({name: 'publishStatus', title: 'Publish status', type: 'publishStatus', group: 'display'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
  ],
  orderings: [
    {name: 'published', title: 'Published date', by: [{field: 'publishedAt', direction: 'desc'}]},
    {name: 'order', title: 'Display order', by: [{field: 'displayOrder', direction: 'asc'}]},
    {name: 'type', title: 'Article type', by: [{field: 'articleType', direction: 'asc'}]},
  ],
  preview: {select: {title: 'title', subtitle: 'articleType', media: 'featuredImage'}},
  validation: createRiskValidation(['title', 'excerpt']),
})
