import {defineField, defineType} from 'sanity'
import {CaseIcon} from '@sanity/icons'
import {createRiskValidation} from '../validation'

export const caseStudy = defineType({
  name: 'caseStudy',
  title: 'Case Studies',
  type: 'document',
  icon: CaseIcon,
  groups: [{name: 'basic', title: 'Basic'}, {name: 'buyer', title: 'Buyer'}, {name: 'content', title: 'Content'}, {name: 'result', title: 'Result'}, {name: 'seo', title: 'SEO'}],
  fields: [
    defineField({name: 'projectTitle', title: 'Project title', type: 'string', group: 'basic', validation: (Rule) => Rule.required()}),
    defineField({name: 'caseType', title: 'Case type', type: 'string', group: 'basic'}),
    defineField({name: 'realOrExample', title: 'Real or example status', type: 'string', group: 'basic', options: {list: [
      {title: 'Real Project', value: 'real'},
      {title: 'Anonymized Real Project', value: 'anonymized'},
      {title: 'Example Project Scenario', value: 'example'},
    ]}, initialValue: 'example'}),
    defineField({name: 'title', title: 'Legacy title fallback', type: 'string', group: 'basic'}),
    defineField({name: 'slug', title: 'URL slug', type: 'slug', group: 'basic', options: {source: 'projectTitle', maxLength: 80}, validation: (Rule) => Rule.required()}),
    defineField({name: 'country', title: 'Country', type: 'string', group: 'buyer'}),
    defineField({name: 'countryOrRegion', title: 'Country or region', type: 'string', group: 'buyer'}),
    defineField({name: 'buyerName', title: 'Buyer name', type: 'string', group: 'buyer', description: 'Use only when the customer has approved public naming.'}),
    defineField({name: 'buyerType', title: 'Buyer type', type: 'string', group: 'buyer'}),
    defineField({name: 'region', title: 'Region', type: 'string', group: 'buyer'}),
    defineField({name: 'quantityDisplay', title: 'Quantity display', type: 'string', group: 'buyer'}),
    defineField({name: 'projectTimeline', title: 'Project timeline', type: 'string', group: 'buyer'}),
    defineField({name: 'product', title: 'Product', type: 'string', group: 'basic'}),
    defineField({name: 'productType', title: 'Product type', type: 'string', group: 'basic'}),
    defineField({name: 'heroImage', title: 'Hero image', type: 'imageWithAlt', group: 'content'}),
    defineField({name: 'images', title: 'Case images', type: 'array', of: [{type: 'imageWithAlt'}], group: 'content'}),
    defineField({name: 'projectBackground', title: 'Project background', type: 'text', rows: 4, group: 'content'}),
    defineField({name: 'challenge', title: 'Challenge', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'requirements', title: 'Requirements', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'overview', title: 'Overview', type: 'text', rows: 4, group: 'content'}),
    defineField({name: 'solution', title: 'Solution', type: 'text', rows: 4, group: 'content'}),
    defineField({name: 'materials', title: 'Materials', type: 'text', rows: 2, group: 'content'}),
    defineField({name: 'customization', title: 'Customization', type: 'text', rows: 2, group: 'content'}),
    defineField({name: 'sampleProcess', title: 'Sample process', type: 'text', rows: 2, group: 'content'}),
    defineField({name: 'production', title: 'Production', type: 'text', rows: 2, group: 'content'}),
    defineField({name: 'qualityControl', title: 'Quality control', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'qcProcess', title: 'QC process', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'packingDelivery', title: 'Packing and delivery', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'packaging', title: 'Packaging', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'delivery', title: 'Delivery', type: 'text', rows: 2, group: 'result'}),
    defineField({name: 'result', title: 'Result', type: 'text', rows: 3, group: 'result'}),
    defineField({name: 'testimonial', title: 'Testimonial', type: 'text', rows: 3, group: 'result', description: 'Use only with buyer approval.'}),
    defineField({name: 'buyerFeedback', title: 'Buyer feedback', type: 'text', rows: 3, group: 'result', description: 'Use only with buyer approval.'}),
    defineField({name: 'evidenceStatus', title: 'Evidence status', type: 'string', group: 'result', options: {list: [
      {title: 'Verified public evidence', value: 'verified'},
      {title: 'Internal evidence only', value: 'internal'},
      {title: 'Example scenario', value: 'example'},
      {title: 'Not publicly disclosed', value: 'notPublic'},
    ]}, initialValue: 'example'}),
    defineField({name: 'relatedProducts', title: 'Related products', type: 'array', of: [{type: 'reference', to: [{type: 'product'}]}], group: 'result'}),
    defineField({name: 'relatedGuides', title: 'Related guides', type: 'array', of: [{type: 'reference', to: [{type: 'article'}]}], group: 'result'}),
    defineField({name: 'cta', title: 'CTA', type: 'callToAction', group: 'result'}),
    defineField({name: 'displayOrder', title: 'Display order', type: 'number', initialValue: 0, group: 'seo'}),
    defineField({name: 'publishStatus', title: 'Publish status', type: 'publishStatus', group: 'seo'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
  ],
  preview: {select: {title: 'projectTitle', subtitle: 'country', media: 'heroImage'}},
  validation: createRiskValidation(['projectTitle', 'projectBackground', 'overview', 'solution', 'buyerFeedback']),
})
