import {defineField, defineType} from 'sanity'
import {TagIcon} from '@sanity/icons'
import {createRiskValidation} from '../validation'

export const productCategory = defineType({
  name: 'productCategory',
  title: 'Product Categories',
  type: 'document',
  icon: TagIcon,
  groups: [{name: 'basic', title: 'Basic'}, {name: 'content', title: 'Content'}, {name: 'display', title: 'Display'}, {name: 'seo', title: 'SEO'}],
  fields: [
    defineField({name: 'categoryName', title: 'Category name', type: 'string', group: 'basic', validation: (Rule) => Rule.required()}),
    defineField({name: 'shortName', title: 'Short name', type: 'string', group: 'basic'}),
    defineField({name: 'slug', title: 'URL slug', type: 'slug', group: 'basic', options: {source: 'categoryName', maxLength: 80}, validation: (Rule) => Rule.required()}),
    defineField({name: 'heroTitle', title: 'Hero title', type: 'string', group: 'content'}),
    defineField({name: 'heroDescription', title: 'Hero description', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'introduction', title: 'Introduction', type: 'text', rows: 4, group: 'content'}),
    defineField({name: 'heroImage', title: 'Hero image', type: 'imageWithAlt', group: 'content'}),
    defineField({name: 'heroProofPoints', title: 'Hero proof points', type: 'array', of: [{type: 'string'}], group: 'content', validation: (Rule) => Rule.max(6)}),
    defineField({name: 'decisionSections', title: 'Buying decision sections', type: 'array', of: [{type: 'pageSection'}], group: 'content'}),
    defineField({name: 'buyerTypes', title: 'Buyer types', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'targetMarkets', title: 'Target markets', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'productTypes', title: 'Product types', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'keyFeatures', title: 'Key features', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'coreBenefits', title: 'Core benefits', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'taxonomyGroup', title: 'Canonical taxonomy group', type: 'string', group: 'basic', options: {list: ['SPORTS', 'TEAMWEAR', 'MANUFACTURING_SOLUTIONS']}}),
    defineField({name: 'taxonomyKey', title: 'Canonical taxonomy key', type: 'string', group: 'basic'}),
    defineField({name: 'claimPolicies', title: 'Truth claim policies', type: 'array', group: 'content', of: [{type: 'claimPolicy'}]}),
    defineField({name: 'evidenceRecords', title: 'Evidence records', type: 'array', group: 'content', of: [{type: 'reference', to: [{type: 'evidenceRecord'}]}]}),
    defineField({name: 'defaultProcurementStandards', title: 'Default procurement standards', type: 'reference', to: [{type: 'procurementStandards'}], group: 'content'}),
    defineField({name: 'relatedFaqs', title: 'Related FAQ', type: 'array', of: [{type: 'faqReference'}], group: 'content'}),
    defineField({name: 'relatedCaseStudies', title: 'Related case studies', type: 'array', of: [{type: 'reference', to: [{type: 'caseStudy'}]}], group: 'content'}),
    defineField({name: 'relatedGuides', title: 'Related guides', type: 'array', of: [{type: 'reference', to: [{type: 'article'}]}], group: 'content'}),
    defineField({name: 'primaryCta', title: 'Primary CTA', type: 'callToAction', group: 'content'}),
    defineField({name: 'secondaryCta', title: 'Secondary CTA', type: 'callToAction', group: 'content'}),
    defineField({name: 'bottomCta', title: 'Bottom CTA', type: 'callToAction', group: 'content'}),
    defineField({name: 'navigationVisibility', title: 'Show in navigation', type: 'boolean', initialValue: true, group: 'display'}),
    defineField({name: 'homepageVisibility', title: 'Show on homepage', type: 'boolean', initialValue: false, group: 'display'}),
    defineField({name: 'showOnHomepage', title: 'Show on homepage (legacy)', type: 'boolean', initialValue: false, group: 'display'}),
    defineField({name: 'activeStatus', title: 'Active status', type: 'boolean', initialValue: true, group: 'display'}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', initialValue: false, group: 'display'}),
    defineField({name: 'displayOrder', title: 'Display order', type: 'number', initialValue: 0, group: 'display'}),
    defineField({name: 'publishStatus', title: 'Publish status', type: 'publishStatus', group: 'display'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
  ],
  orderings: [{name: 'order', title: 'Display order', by: [{field: 'displayOrder', direction: 'asc'}]}],
  preview: {select: {title: 'categoryName', subtitle: 'slug.current', media: 'heroImage'}},
  validation: createRiskValidation(['categoryName', 'heroTitle', 'heroDescription', 'introduction', 'heroProofPoints', 'decisionSections']),
})
