import {defineField, defineType} from 'sanity'
import {DocumentsIcon} from '@sanity/icons'
import {createRiskValidation} from '../validation'

export const sitePage = defineType({
  name: 'sitePage',
  title: 'Site Pages',
  type: 'document',
  icon: DocumentsIcon,
  groups: [
    {name: 'basic', title: 'Basic'},
    {name: 'hero', title: 'Hero'},
    {name: 'content', title: 'Content'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'internalName', title: 'Internal page name', type: 'string', group: 'basic', validation: (Rule) => Rule.required()}),
    defineField({name: 'pageKey', title: 'Page key', type: 'string', group: 'basic', description: 'Stable key used by the frontend, for example homepage, about, factory, contact.', validation: (Rule) => Rule.required()}),
    defineField({
      name: 'pageType',
      title: 'Page template type',
      type: 'string',
      group: 'basic',
      options: {
        list: [
          {title: 'Homepage', value: 'homepage'},
          {title: 'About', value: 'about'},
          {title: 'Factory', value: 'factory'},
          {title: 'Manufacturing', value: 'manufacturing'},
          {title: 'Quality Control', value: 'qualityControl'},
          {title: 'Customization', value: 'customization'},
          {title: 'OEM / ODM', value: 'oemOdm'},
          {title: 'Free Mockup', value: 'freeMockup'},
          {title: 'Sample Order', value: 'sampleOrder'},
          {title: 'Get Quote', value: 'getQuote'},
          {title: 'Contact', value: 'contact'},
          {title: 'Products Landing', value: 'productsLanding'},
          {title: 'Projects Landing', value: 'projectsLanding'},
          {title: 'Guides Landing', value: 'guidesLanding'},
          {title: 'Resources Landing', value: 'resourcesLanding'},
          {title: 'Blog Landing', value: 'blogLanding'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'slug', title: 'URL slug', type: 'slug', group: 'basic', options: {source: 'internalName'}}),
    defineField({name: 'heroEyebrow', title: 'Hero eyebrow', type: 'string', group: 'hero'}),
    defineField({name: 'heroHeading', title: 'Hero H1', type: 'string', group: 'hero'}),
    defineField({name: 'heroSubheading', title: 'Hero description', type: 'text', rows: 3, group: 'hero'}),
    defineField({name: 'heroImage', title: 'Hero image', type: 'imageWithAlt', group: 'hero'}),
    defineField({name: 'heroCTA', title: 'Hero CTA', type: 'callToAction', group: 'hero'}),
    defineField({name: 'heroSecondaryCTA', title: 'Hero secondary CTA', type: 'callToAction', group: 'hero'}),
    defineField({
      name: 'homepageUspCards',
      title: 'Homepage USP cards',
      type: 'array',
      group: 'content',
      of: [{
        type: 'object',
        fields: [
          defineField({name: 'metric', title: 'Metric', type: 'string'}),
          defineField({name: 'title', title: 'Title', type: 'string'}),
          defineField({name: 'description', title: 'Description', type: 'text', rows: 3}),
          defineField({name: 'displayOrder', title: 'Display order', type: 'number'}),
        ],
        preview: {select: {title: 'title', subtitle: 'metric'}},
      }],
    }),
    defineField({
      name: 'homepageSectionHeadings',
      title: 'Homepage section headings',
      type: 'object',
      group: 'content',
      fields: [
        defineField({name: 'sourcingEyebrow', title: 'Factory sourcing eyebrow', type: 'string'}),
        defineField({name: 'sourcingTitle', title: 'Factory sourcing title', type: 'string'}),
        defineField({name: 'sourcingSubtitle', title: 'Factory sourcing subtitle', type: 'text', rows: 2}),
        defineField({name: 'uspEyebrow', title: 'USP eyebrow', type: 'string'}),
        defineField({name: 'uspTitle', title: 'USP title', type: 'string'}),
        defineField({name: 'uspSubtitle', title: 'USP subtitle', type: 'text', rows: 2}),
        defineField({name: 'matrixEyebrow', title: 'Product matrix eyebrow', type: 'string'}),
        defineField({name: 'matrixTitle', title: 'Product matrix title', type: 'string'}),
        defineField({name: 'faqEyebrow', title: 'FAQ eyebrow', type: 'string'}),
        defineField({name: 'faqTitle', title: 'FAQ title', type: 'string'}),
      ],
    }),
    defineField({
      name: 'homepageOptimization',
      title: 'V1.1 homepage copy and FAQ',
      type: 'object',
      group: 'content',
      description: 'Published copy for the nine-module homepage. Module order, product links, supplied asset paths, form rules and CTA destinations are fixed in code. Review commercial claims before publishing.',
      fields: [
        defineField({name: 'heroEyebrow', title: 'Hero eyebrow', type: 'string', validation: Rule => Rule.max(80)}),
        defineField({name: 'heroHeading', title: 'Hero H1', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'heroDescription', title: 'Hero description', type: 'text', rows: 3, validation: Rule => Rule.max(500)}),
        defineField({name: 'heroWelcome', title: 'Hero buyer welcome', type: 'string', validation: Rule => Rule.max(180)}),
        defineField({name: 'heroMicrocopy', title: 'Hero action note', type: 'string', validation: Rule => Rule.max(180)}),
        defineField({name: 'sportsHeading', title: 'Module 2 heading', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'buyersHeading', title: 'Module 3 heading', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'detailsHeading', title: 'Module 4 heading', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'mockupHeading', title: 'Module 5 heading', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'sampleHeading', title: 'Module 6 heading', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'productionHeading', title: 'Module 7 heading', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'faqHeading', title: 'Module 8 heading', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'contactHeading', title: 'Module 9 heading', type: 'string', validation: Rule => Rule.max(130)}),
        defineField({name: 'faqs', title: 'Nine buyer FAQs', type: 'array', validation: Rule => Rule.max(9), of: [{type: 'object', fields: [
          defineField({name: 'question', title: 'Question', type: 'string', validation: Rule => Rule.required().max(180)}),
          defineField({name: 'answer', title: 'Answer', type: 'text', rows: 3, validation: Rule => Rule.required().max(700)}),
        ]}] }),
      ],
    }),
    defineField({
      name: 'inquirySupport',
      title: 'Homepage inquiry support box',
      type: 'object',
      group: 'content',
      fields: [
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 3}),
      ],
    }),
    defineField({name: 'contentSections', title: 'Main content modules', type: 'array', group: 'content', of: [{type: 'pageSection'}]}),
    defineField({name: 'productionMedia', title: 'Verified production media', type: 'productionMediaSet', group: 'content', description: 'Optional V8 media slots. Unverified assets remain hidden on the website.'}),
    defineField({name: 'bottomCTA', title: 'Bottom CTA', type: 'callToAction', group: 'content'}),
    defineField({name: 'relatedProducts', title: 'Related products', type: 'array', of: [{type: 'reference', to: [{type: 'product'}]}], group: 'content'}),
    defineField({name: 'relatedCases', title: 'Related case studies', type: 'array', of: [{type: 'reference', to: [{type: 'caseStudy'}]}], group: 'content'}),
    defineField({name: 'relatedFaqs', title: 'Related FAQ', type: 'array', of: [{type: 'faqReference'}], group: 'content'}),
    defineField({name: 'lastReviewedAt', title: 'Last reviewed at', type: 'datetime', group: 'seo'}),
    defineField({name: 'noindex', title: 'No-index page', type: 'boolean', initialValue: false, group: 'seo'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
    defineField({name: 'publishStatus', title: 'Publish status', type: 'publishStatus', group: 'seo'}),
  ],
  preview: {select: {title: 'internalName', subtitle: 'pageKey'}},
  validation: createRiskValidation(['internalName', 'heroHeading', 'heroSubheading']),
})
