import {defineField, defineType} from 'sanity'
import {DocumentsIcon} from '@sanity/icons'
import {createRiskValidation} from '../validation'

export const sitePage = defineType({
  name: 'sitePage',
  title: 'Site Pages',
  type: 'document',
  icon: DocumentsIcon,
  groups: [
    {name: 'basic', title: 'Basic'},
    {name: 'hero', title: 'Hero'},
    {name: 'content', title: 'Content'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'internalName', title: 'Internal page name', type: 'string', group: 'basic', validation: (Rule) => Rule.required()}),
    defineField({name: 'pageKey', title: 'Page key', type: 'string', group: 'basic', description: 'Stable key used by the frontend, for example homepage, about, factory, contact.', validation: (Rule) => Rule.required()}),
    defineField({
      name: 'pageType',
      title: 'Page template type',
      type: 'string',
      group: 'basic',
      options: {
        list: [
          {title: 'Homepage', value: 'homepage'},
          {title: 'About', value: 'about'},
          {title: 'Factory', value: 'factory'},
          {title: 'Manufacturing', value: 'manufacturing'},
          {title: 'Quality Control', value: 'qualityControl'},
          {title: 'Customization', value: 'customization'},
          {title: 'OEM / ODM', value: 'oemOdm'},
          {title: 'Free Mockup', value: 'freeMockup'},
          {title: 'Sample Order', value: 'sampleOrder'},
          {title: 'Get Quote', value: 'getQuote'},
          {title: 'Contact', value: 'contact'},
          {title: 'Products Landing', value: 'productsLanding'},
          {title: 'Projects Landing', value: 'projectsLanding'},
          {title: 'Guides Landing', value: 'guidesLanding'},
          {title: 'Resources Landing', value: 'resourcesLanding'},
          {title: 'Blog Landing', value: 'blogLanding'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'slug', title: 'URL slug', type: 'slug', group: 'basic', options: {source: 'internalName'}}),
    defineField({name: 'heroEyebrow', title: 'Hero eyebrow', type: 'string', group: 'hero'}),
    defineField({name: 'heroHeading', title: 'Hero H1', type: 'string', group: 'hero'}),
    defineField({name: 'heroSubheading', title: 'Hero description', type: 'text', rows: 3, group: 'hero'}),
    defineField({name: 'heroImage', title: 'Hero image', type: 'imageWithAlt', group: 'hero'}),
    defineField({name: 'heroCTA', title: 'Hero CTA', type: 'callToAction', group: 'hero'}),
    defineField({name: 'heroSecondaryCTA', title: 'Hero secondary CTA', type: 'callToAction', group: 'hero'}),
    defineField({
      name: 'homepageUspCards',
      title: 'Homepage USP cards',
      type: 'array',
      group: 'content',
      of: [{
        type: 'object',
        fields: [
          defineField({name: 'metric', title: 'Metric', type: 'string'}),
          defineField({name: 'title', title: 'Title', type: 'string'}),
          defineField({name: 'description', title: 'Description', type: 'text', rows: 3}),
          defineField({name: 'displayOrder', title: 'Display order', type: 'number'}),
        ],
        preview: {select: {title: 'title', subtitle: 'metric'}},
      }],
    }),
    defineField({
      name: 'homepageSectionHeadings',
      title: 'Homepage section headings',
      type: 'object',
      group: 'content',
      fields: [
        defineField({name: 'sourcingEyebrow', title: 'Factory sourcing eyebrow', type: 'string'}),
        defineField({name: 'sourcingTitle', title: 'Factory sourcing title', type: 'string'}),
        defineField({name: 'sourcingSubtitle', title: 'Factory sourcing subtitle', type: 'text', rows: 2}),
        defineField({name: 'uspEyebrow', title: 'USP eyebrow', type: 'string'}),
        defineField({name: 'uspTitle', title: 'USP title', type: 'string'}),
        defineField({name: 'uspSubtitle', title: 'USP subtitle', type: 'text', rows: 2}),
        defineField({name: 'matrixEyebrow', title: 'Product matrix eyebrow', type: 'string'}),
        defineField({name: 'matrixTitle', title: 'Product matrix title', type: 'string'}),
        defineField({name: 'faqEyebrow', title: 'FAQ eyebrow', type: 'string'}),
        defineField({name: 'faqTitle', title: 'FAQ title', type: 'string'}),
      ],
    }),
    defineField({
      name: 'inquirySupport',
      title: 'Homepage inquiry support box',
      type: 'object',
      group: 'content',
      fields: [
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 3}),
      ],
    }),
    defineField({name: 'contentSections', title: 'Main content modules', type: 'array', group: 'content', of: [{type: 'pageSection'}]}),
    defineField({name: 'bottomCTA', title: 'Bottom CTA', type: 'callToAction', group: 'content'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
    defineField({name: 'publishStatus', title: 'Publish status', type: 'publishStatus', group: 'seo'}),
  ],
  preview: {select: {title: 'internalName', subtitle: 'pageKey'}},
  validation: createRiskValidation(['internalName', 'heroHeading', 'heroSubheading']),
})
