"use client";
import { useState } from "react";
import { inquiryTypeOptions } from "@/lib/contact-data";

type ContactFormState = { fullName: string; email: string; phone: string; country: string; inquiryType: string; message: string; };
const initialState: ContactFormState = { fullName: "", email: "", phone: "", country: "", inquiryType: "", message: "" };
function FieldLabel({ children, required = false }: { children: React.ReactNode; required?: boolean }) { return <label className="mb-2 block text-sm font-black text-neutral-950">{children} {required ? <span className="text-lime-600">*</span> : null}</label>; }
const inputClass = "h-[50px] w-full rounded-2xl border border-neutral-300 bg-white px-4 text-sm text-neutral-950 outline-none transition placeholder:text-neutral-400 focus:border-lime-400";

export default function ContactForm() {
  const [form, setForm] = useState<ContactFormState>(initialState);
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  function updateField(name: keyof ContactFormState, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setErrorMessage("");
    try {
      const endpoint = process.env.NEXT_PUBLIC_FORMSPREE_CONTACT_ENDPOINT;
      if (!endpoint) throw new Error("Form endpoint is not configured. Add NEXT_PUBLIC_FORMSPREE_CONTACT_ENDPOINT in Cloudflare Pages.");
      const response = await fetch(endpoint, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify({ formType: "Contact", ...form, sourcePage: window.location.href }) });
      if (!response.ok) throw new Error("Submit failed. Please try again or contact us by email.");
      setSubmitted(true); setForm(initialState);
    } catch (error) { setErrorMessage(error instanceof Error ? error.message : "Something went wrong. Please try again."); } finally { setLoading(false); }
  }
  if (submitted) return <div className="rounded-[2rem] bg-white p-8 shadow-xl md:p-10"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-lime-400 text-2xl font-black text-neutral-950">✓</div><h2 className="mt-6 text-3xl font-black text-neutral-950">Message Sent</h2><p className="mt-4 leading-7 text-neutral-600">Thank you. The POXIOL team has received your message and will review your inquiry.</p><button type="button" onClick={() => setSubmitted(false)} className="mt-8 h-[52px] rounded-full bg-neutral-950 px-7 text-sm font-black uppercase text-white transition hover:bg-lime-400 hover:text-neutral-950">Send Another Message</button></div>;
  return <form onSubmit={handleSubmit} className="rounded-[2rem] bg-white p-6 shadow-xl md:p-9"><div className="mb-8"><p className="text-sm font-black uppercase tracking-[0.14em] text-lime-600">Contact Form</p><h2 className="mt-3 text-3xl font-black text-neutral-950">Send POXIOL a Message</h2><p className="mt-3 text-sm leading-6 text-neutral-600">Tell us what you need. For new design projects, Free Mockup is usually the fastest path.</p></div><div className="grid gap-4 md:grid-cols-2"><div><FieldLabel required>Full Name</FieldLabel><input required value={form.fullName} onChange={(e)=>updateField("fullName",e.target.value)} className={inputClass} placeholder="Your name" /></div><div><FieldLabel required>Email Address</FieldLabel><input required type="email" value={form.email} onChange={(e)=>updateField("email",e.target.value)} className={inputClass} placeholder="your@email.com" /></div><div><FieldLabel>WhatsApp / Phone</FieldLabel><input value={form.phone} onChange={(e)=>updateField("phone",e.target.value)} className={inputClass} placeholder="Country code + phone number" /></div><div><FieldLabel>Country / Region</FieldLabel><input value={form.country} onChange={(e)=>updateField("country",e.target.value)} className={inputClass} placeholder="United States, Germany, UAE..." /></div><div className="md:col-span-2"><FieldLabel required>Inquiry Type</FieldLabel><select required value={form.inquiryType} onChange={(e)=>updateField("inquiryType",e.target.value)} className={inputClass}><option value="">Select inquiry type</option>{inquiryTypeOptions.map((item)=><option key={item} value={item}>{item}</option>)}</select></div><div className="md:col-span-2"><FieldLabel required>Message</FieldLabel><textarea required value={form.message} onChange={(e)=>updateField("message",e.target.value)} className="min-h-[150px] w-full rounded-2xl border border-neutral-300 bg-white p-4 text-sm text-neutral-950 outline-none transition placeholder:text-neutral-400 focus:border-lime-400" placeholder="Tell us about your project, order, cooperation plan or support request." /></div><div className="md:col-span-2 rounded-2xl border border-dashed border-neutral-300 bg-neutral-50 p-5"><p className="text-sm font-black text-neutral-950">Files</p><p className="mt-2 text-sm leading-6 text-neutral-600">Submit the form first. The POXIOL team will reply and ask you to send logos or reference files by email or WhatsApp if needed.</p></div></div>{errorMessage ? <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{errorMessage}</div> : null}<button type="submit" disabled={loading} className="mt-8 h-[56px] w-full rounded-full bg-lime-400 text-sm font-black uppercase tracking-wide text-neutral-950 transition hover:bg-neutral-950 hover:text-white disabled:cursor-not-allowed disabled:opacity-70">{loading ? "Sending..." : "Send Message"}</button></form>;
}
